### PR TITLE
Update deploy.yml

### PR DESCRIPTION
**Pull request by tlienart**
that's the reason why it wasn't triggering

### CODE REVIEW

**Comment by tlienart** [comment]
(you forked this from https://github.com/tlienart2/tlienart2.github.io and it was set to `master` because it pre-dated the change by GitHub to call your principal branch "main" instead of "master", anyway this fixes it, I've also fixed it on the repo you forked from)

**Comment by tlienart** [comment]
looks like you beat me to it, the workflow fails, check whitespaces and then just re-start it (https://github.com/Tobias-Thomas/tobias-thomas.github.io/actions/runs/1736209103)

**Comment by tlienart** [comment]
you got it, nice ;-)

**Comment by Tobias-Thomas** [comment]
Thanks, for the quick and really good help!

**Pull request closed without merging**
